### ISSUE TITLE
differences with react-p5 ?

### ISSUE THREAD

**Issue by dcsan** [P5-wrapper/react#128]
this maybe a silly question but there's another lib with an almost identical API it seems (at first) I was wondering if there are any major differences in the design or choices you made?

https://github.com/Gherciu/react-p5/issues

**Comment by jamesrweb** [comment]
@dcsan Some notes regarding differences between the two:

- The `react-p5` library uses [custom types](https://github.com/Gherciu/react-p5/blob/main/%40types/index.d.ts) rather than a direct extension of `p5` itself.
The `react-p5` library does pass you the `p5` object that is generated to the `setup` and `draw` functions but in a different way to how we do it. We allow you full control over the instance and guarantee it is a pure instance of `p5` without any mutations applied but `react-p5` proxy controls the initial `p5` object generated and overwrites `p5` functions in some places such as [here](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L43), we do not do this here because we view mutation as inappropriate.
- The `react-p5` library uses older react classes and [doesn't react to prop changes](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L52) like we do but instead just [runs a sketch](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L38).
- We implemented this library extends `p5` in a pure sense and doesn't mess with any of its internal.
- We use modern, clean, functional style react code (version 16.8+ supported) and allow you to pass props into your sketches to react to and use as you see fit.
- We guarantee that there is no unnecessary re-rendering when props change whereas `react-p5` [doesn't allow you](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L52) to react to prop changes at all.
- We have first class support for TypeScript and export highly specific interfaces for every single touch point you may use from this library.
- We don't mess with globals like `react-p5` [does](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L6).
- We don't mess with `p5` methods or internals like `react-p5` [does](https://github.com/Gherciu/react-p5/blob/c2518b7fdc92a0c215cf4f9e7c6288fa9a6cfed6/src/index.jsx#L44).

Theres some differences for you, hope that helps.

**Comment by yevdyko** [comment]
@jamesrweb these details may also be part of the documentation, right?

**Comment by jamesrweb** [comment]
@yevdyko I think that makes sense but I would rather do it as part of #107 so that we don't expand the readme file too much, WDYT?

**Comment by yevdyko** [comment]
> @yevdyko I think that makes sense but I would rather do it as part of #107 so that we don't expand the readme file too much, WDYT?

Yes, agree. We can mention it in #107  and link them.

**Comment by dcsan** [comment]
thanks for the super detailed reply! Certainly seems like an active project here!

I did try out the other lib first and hit some issues, had the questions for you here.

How do you provide access to static methods [such as map](https://p5js.org/reference/#/p5/map)
(this one is named a bit riskily imho but it's part of p5)

```
const range = (map(val, 65, 90, 0, 255))
```

and also constant enums eg `BLEND`

is there a way to access these without a p5 instance?

**Comment by jamesrweb** [comment]
No, as the documentation shows, you must define a sketch function that takes `p5` instance as an argument, this will provide you with such things, and then pass that function to the wrapper component:

```js
function sketch(p5) {
  let v = 0;
  
  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.draw = () => {
   const c = p5.map(v, 65, 90, 0, 255);
   
    p5.background(c);
    p5.normalMaterial();
    p5.push();
    p5.rotateZ(p5.frameCount * 0.01);
    p5.rotateX(p5.frameCount * 0.01);
    p5.rotateY(p5.frameCount * 0.01);
    p5.plane(100);
    p5.pop();
    
    v++;
  };
}

export default function App() {
  return <ReactP5Wrapper sketch={sketch} />;
}
```

This is a standard [P5 instance mode](https://p5js.org/examples/instance-mode-instantiation.html) setup.

**Comment by dcsan** [comment]
Yes I understand that for methods that need a context, however there are many convenient (static) methods and constants, I would have thought those might be available, just through a types/constants method?

that original p5 instance is only available at one point and I don't want to put it in global namespace, or pass it around all over the app.

I did this in another (non react) app

```ts
// This file will add both p5 instanced and global intellisence
import module = require('p5');
import * as p5Global from 'p5/global'

export = module;
export as namespace p5;


declare global {
  interface Window {
    p5: typeof module,
    newToken: any
  }
}

```

perhaps I can just import the typings directly? Or would that clash with your react module?

**Comment by jamesrweb** [comment]
I have no idea, try it but this component won't expose globals because it's not necessary. If you need the constants outside of your sketch for some reason you'll need to import them directly from P5 somehow. I wouldn't recommend doing this though because it pollutes the global namespace and also might clash with the instance mode sketch.

**Comment by jamesrweb** [comment]
Closing the issue since there's nothing to solve in the codebase.
