### ISSUE TITLE
Drawing new line instead of updating existing one

### ISSUE THREAD

**Issue by F-Moody** [P5-wrapper/react#35]
Hi, 
i'm trying to draw a rainfall.
If i do this on p5online editor it works, it creates a single rain drop that falls over the screen.

If i use this with p5wrapper it draws multiple drops one under the other every call of "draw" function. 
Here's my sketch : 

> `import RainDrop from '../Models/RainDrop'

export default function sketch (p) {

    const drop = new RainDrop(p)

    p.setup = function () {
        p.createCanvas(window.innerWidth, window.innerHeight)
    };

    p.myCustomRedrawAccordingToNewPropsHandler = function (props) {
        console.log(props, 'custom thing')
    };

    p.draw = function () {
        drop.draw()
        drop.update()

    };
};`

here's my RainDrop class

    `export default class RainDrop {
    constructor(p) {
        this.x = Math.floor(Math.random() * window.innerWidth) + 1
        //this.y = Math.floor(Math.random() * -500)
        this.y = 50
        this.speed = Math.floor(Math.random() * 10) + 1
        this.p = p
    }

    update = () => {
        this.y = this.y + 10//this.speed
        if(this.y > window.innerHeight) {
            this.y = Math.floor(Math.random() * -500)
        }
    }

    draw = () => {
        this.p.stroke(128,0,128)
        this.p.line(this.x, this.y, this.x, this.y + 5)
    }
}`

and here's my simple App.js :
    `import React from 'react';
      import logo from './logo.svg';
      import './App.css';
      import P5Wrapper from 'react-p5-wrapper'
      import MouseSketch from './Sketches/MouseSketch'
      import RainingSketch from './Sketches/RainingSketch'

       function App() {
           return (
             <div className="App">
                <P5Wrapper sketch={RainingSketch} />
             </div>
         );
         }

          export default App;`

**Comment by CubeOfCheese** [comment]
You accidentally posted your sketch.js twice instead of your raindrop class.
I think you might be able to work around this by pushing and popping your raindrop object to an array and drawing that array. I also opened an issue that worked in the p5 online simulator, so maybe our problems are related.

**Comment by F-Moody** [comment]
Thanks! fixed that.

**Comment by CubeOfCheese** [comment]
I am running into the same problem as you are now and I tested my suggestion of using an array, but I realized that it does not have any effect. What is interesting is that they are not all independent objects, they are only left over images of where the object used to be.

**Comment by CubeOfCheese** [comment]
I believe that this is not only a problem with objects but also regular p5 drawings such as in this example.
`p5.draw = function () {
    p5.ellipse(p5.mouseX,  p5.mouseY, 30);
}
`
Rather than having a circle follow my mouse as it should, it leaves a trail of circles as shown here.

![Screen Shot 2019-07-08 at 4 18 58 PM](https://user-images.githubusercontent.com/16740469/60848634-4076ac00-a19c-11e9-8f01-39b3510988ed.png)

**Comment by and-who** [comment]
Question, do you clear the FrameBuffer on the beginning of the new draw cycle?
e.g. with setting the Background?
https://github.com/and-who/react-p5-wrapper/blob/2275f7972522b8b6a449a5cea2e1a79e9acb5d3b/example/src/sketches/sketch.js#L15

**Comment by F-Moody** [comment]
Funny enough, i've just tried that and it works now.
Can you explain me why?

**Comment by and-who** [comment]
I assume the following, since it works in other GraphicSystems similar.

p5 stores the calculated Image in an FrameBuffer.
To clear the Frame Buffer would be additional operations, so why not keep it, because you could use it in your next Frame.

I actually have an Example how you could use it :D
On my Webpage I create a nice Effect by drawing with some Transparency over my last rendered image and moving the circles a bit:
http://wolfandreas.com/

**Comment by CubeOfCheese** [comment]
Wow! Thank you. I think this issue can be closed now. This makes total sense now.
