### ISSUE TITLE
Add support for React 17

### ISSUE THREAD

**Issue by disambiguator** [P5-wrapper/react#70]
Can the package.json be updated to allow for React 17?

**Comment by jamesrweb** [comment]
The package doesn't stop you using react 17, is there a specific issue you have seen or just an assumption that it wouldn't work?

**Comment by jamesrweb** [comment]
I updated the dependencies in PR #71 and merged it. It will be released at the next possible point. For now though I see no reason you shouldn't be able to use the library as is? Happy to help if you can explain further though.

**Comment by jamesrweb** [comment]
Closing for now.

**Comment by disambiguator** [comment]
@jamesrweb Great thank you! I am seeing this when running `npm update`

```
❯ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: floating_points@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-p5-wrapper@2.3.0
npm ERR! node_modules/react-p5-wrapper
npm ERR!   react-p5-wrapper@"^2.3.0" from the root project
```

I figured there wouldn't actually be incompatible, thank you.

**Comment by jamesrweb** [comment]
Peer dependencies are a tricky one with NPM, honestly I don't think we need them for the project but I don't want to remove them without feedback on why they were there in the first place.

For now I am the one working mostly on the repo and so all I can say is that in the future when v3 is complete (see initial PR #65) there will also be a tidying up of how dependencies, builds and configurations are handled. I plan to implement those in the next step once I fix the current re-rendering issue in that PR.

I need @and-who to do the NPM releases of the codebase (which includes quite a few changes already) since I don't have permissions to do so but he is quite busy currently so I hope he will be able to do this sometime this month but you will be notified once it is done either way.

Hopefully that will resolve the issue once and for all but for now I have done all I can in terms of altering the package.json for you.

**Comment by disambiguator** [comment]
I really appreciate it. I've never published my own package and have been curious how to keep these things up to date in a hassle-free way, so learning a lot here. :) Thanks for maintaining this!
