### ISSUE TITLE
prepending everything with p

### ISSUE THREAD

**Issue by joseph-allen** [P5-wrapper/react#75]
I am wondering if there is a way to copy and paste P5 code without needing to prepend every Processing function with p.

for example
```
const circleTest = (p) => {
      
      p.setup = () => {
        p.createCanvas(p.windowWidth / 1.4, p.windowHeight / 2);
        p.background(220);
    }

    p.draw = () => {
        p.circle(p.random(p.width),p.random(p.height),15)
        p.circle(p.mouseX,p.mouseY,50)
    }

    p.windowResized = () => {
        p.resizeCanvas(p.windowWidth / 1.4, p.windowHeight / 2);
    }
    
}
export default circleTest
```

The setup function could be

```
      setup = () => {
        createCanvas(windowWidth / 1.4, windowHeight / 2);
        background(220);
    }
```

**Comment by jamesrweb** [comment]
You could use [the `with` keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with) but that is not a recommended keyword to use. As per the documentation:

```txt
Use of the `with` statement is not recommended, as it may be the source of confusing bugs and compatibility issues.
```

Otherwise, no, there is no way to do this because this is a part of the[`p5` instance mode](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) and we can't work around that, plus it doesn't make sense to do so as the `p5` internal rendering process passes the current state as the `p` param in your case and without it, instance mode would have no way of giving you the current state to update in the next frame.
