### ISSUE TITLE
Questions about classes

### ISSUE THREAD

**Issue by lewiswolf** [P5-wrapper/react#84]
I have two questions about using classes with react. 

I've been using p5 to create dynamic UI that I can place around my page. For each UI element, I want to split up code into classes and have a sketch.js which imports each UI element before going to react. Something along the lines of...

_ui.js_
```js
export default class UI {
	constructor(x, y, d) {
		this.circle = p5.ellipse(x, y, d)
	}

	...

}
```

_sketch.js_
```js
import UI from './ui'

export default function sketch(p5) {
	let ui

	p5.setup = () => {
		ui = new UI(x, y, d)
	}

	...

}
```

However, in practice p5 is not scoped to the file containing the class. I tried importing p5 into the class ( `import p5` ), with no luck. The only way I was able to get it to work is shown below, but I feel like I'm missing something. Please let me know if there is an easier way to do this?

_ui.js_
```js
export default function UI(props, p5) {
	class UI
		constructor(x, y, d) {
			this.circle = p5.ellipse(x, y, d)
		}

		...

	}
	return new UI(props.x, props.y, props.d)
}
```

Secondly, as I've been making UI elements, I've been messing about a lot with event listeners. I did some testing, and it appears that native event listeners ( `window.addEventListener(...)` ) fire before the p5 ones ( `p5.mousePressed( ... )` ), and for this reason I've constructed my UI around native event listeners. Is there anything similar to react's componentWillUnmount() in p5 or the react-p5-wrapper where I can write `window.removeEventListener`? Or is there some clever garbage cleanup going on, that react doesn't do when loading and unloading components? 

Thanks!

**Comment by jamesrweb** [comment]
In answer to your first question:

You would have to use [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) like you did before, this is because between modules variables are not reachable and are scoped to that file and thus an explicit reference must be sent, it is also a tenant of OOP to use dependency injection and only provide what is needed for an object to work. To this end I would structure your code like so:

*index.js*

This file is incharge of rendering the app into an element with the id or "root".

```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(<App />, document.getElementById('root'));
```

*App.js*

This file is in charge of piecing together our app for rendering.

```js
import React from 'react';
import { sketch } from "./sketch"
import P5Wrapper from "react-p5-wrapper";

function App() {
  return <P5Wrapper sketch={sketch} />;
}

export default App;
```

*sketch.js*

This file represents our sketch and utilises our `UI` class, notice how we pass dependencies into the constructor.

```js
import { UI } from './UI'

export function sketch(p5) {
  const ui = new UI(p5)
  
  p5.setup = () => {
    ui.setCircle(10, 20, 5)
  }
}
```

*UI.js*

This is where we write the business logic for our UI class, notice how we only pass values required for a method or constructor to do the minimum required for things to work.

```js
export class UI {
  constructor(p5) {
    this.p5 = p5;
  }

  setCircle(x, y, d) {
    this.circle = this.p5.ellipse(x, y, d)
  }
}
```

I highly recommend reading the [linked article](https://en.wikipedia.org/wiki/Dependency_injection) to understand how the process works.

In answer to your second question:

You can write it where you add the listener, [this is an article on event listeners in react that you may find interesting](https://www.pluralsight.com/guides/how-to-cleanup-event-listeners-react) but in short you could do something like:

```js
import React, { useEffect } from "react";


function myComponentListener(event) {}

function MyComponent(props) {
  ...
  useEffect(() => {
    window.addEventListener(myComponentListener);
    
    return () => {
      window.removeEventListener(myComponentListener);
    }
  })
  ...
}
```

I don't personally see a use case where using native listeners is better that P5 built ins just because of call order, P5 wraps the native listeners for you so that you don't need to do so much manual work but of course it is up to you how you write your own code!

**Comment by lewiswolf** [comment]
Thanks for your response
